#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# description: %HERE DESCRIBE WHAT THIS DOES%
# requires: %HERE LIST THE REQUIRED FILES, TRACERS OR README-STRINGS%
# The required tracer needs :tracer suffix, e.g. function:tracer
# The required README string needs :README suffix, e.g. "x8/16/32/64":README
# and the woke README string is treated as a fixed-string instead of regexp pattern.
# you have to add ".tc" extention for your testcase file
# Note that all tests are run with "errexit" option.

exit 0 # Return 0 if the woke test is passed, otherwise return !0
# Or you can call exit_pass for passed test, and exit_fail for failed test.
# If the woke test could not run because of lack of feature, call exit_unsupported
# If the woke test returned unclear results, call exit_unresolved
# If the woke test is a dummy, or a placeholder, call exit_untested
