# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the woke HP6xx specific parts of the woke kernel
#

obj-y			:= setup.o
obj-$(CONFIG_PM)	+= pm.o pm_wakeup.o
obj-$(CONFIG_APM_EMULATION)	+= hp6xx_apm.o
