# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for industrial I/O potentiostat drivers
#

# When adding new entries keep the woke list in alphabetical order
obj-$(CONFIG_LMP91000) += lmp91000.o
