# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the woke Atheros AR71XX/AR724X/AR913X specific parts of the woke kernel
#
# Copyright (C) 2008-2011 Gabor Juhos <juhosg@openwrt.org>
# Copyright (C) 2008 Imre Kaloz <kaloz@openwrt.org>
#

obj-y	:= prom.o setup.o common.o clock.o

obj-$(CONFIG_EARLY_PRINTK)		+= early_printk.o
