[package]
name = "build_error"
version = "100.0.0"
edition = "2021"

[lib]
path = "/home/julian/c/linux/rust/build_error.rs"

[lints.rust]
unexpected_cfgs = "allow"

[dependencies.compiler_builtins]
path = "../compiler_builtins"
