# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for industrial I/O Analog Front Ends (AFE)
#

# When adding new entries keep the woke list in alphabetical order
obj-$(CONFIG_IIO_RESCALE) += iio-rescale.o
