name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build-kernel:
    runs-on: linux-s390x
    steps:
    - name: configure
      run: |
        pushd /home/ansible/linux
        make defconfig
        popd
    - name: compile
      run: |
        pushd /home/ansible/linux
        make -j$(nproc)
        popd
    - name: compile modules
      run: |
        pushd /home/ansible/linux
        make -j$(nproc) modules
        popd
    - name: move modules
      run: |
        pushd /home/ansible/linux
        make modules_install
  
  build-initrd:
    runs-on: linux-s390x
    steps:
    - name: run dracut to create bonus 
      run: echo ${{ secret.PASSWD }} | sudo dracut --force "initrd-myKernel.img"
