name: C/C++ CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - type: all
            os: ubuntu-24.04-arm
          - type: bindeb-pkg
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        max-size: 1536M
    - run: sudo apt update && sudo apt install -y bc bison flex gcc make libelf-dev libssl-dev debhelper-compat debhelper build-essential ccache device-tree-compiler
    - run: mv scripts/package/mkdeb scripts/package/mkdebian -v
    - run: make -j16 lmi_defconfig ${{ matrix.type }}
